chore: 7 trivy scan vunerabilities

diff --git a/.github/workflows/trivy-scan.yml b/.github/workflows/trivy-scan.yml
--- a/.github/workflows/trivy-scan.yml
+++ b/.github/workflows/trivy-scan.yml
@@ -59,20 +59,27 @@ jobs:
         run: |
           curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Trivy Report uploaded to S3 :white_check_mark:\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
 
-      - name: Upload Trivy report to Slack
+      - name: Send Slack Message - Uploading Report to Slack
         env:
           SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
+          SLACK_CHANNEL: "#experiments"
+          SLACK_TITLE: "Trivy Report ${TIMESTAMP}"
+          SLACK_INITIAL_MESSAGE: "Uploading Trivy Report to Slack :file_upload:"
+          SLACK_UPLOAD_MESSAGE: "Trivy Report uploaded to Slack :white_check_mark:"
         run: |
-          TIMESTAMP=$(date +%Y%m%d)
-          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
-          SLACK_CHANNEL="#experiments"
-          SLACK_TITLE="Trivy Report ${TIMESTAMP}"
-          SLACK_INITIAL_MESSAGE="Uploading Trivy Report to Slack :file_upload:"
-          SLACK_UPLOAD_MESSAGE="Trivy Report uploaded to Slack :white_check_mark:"
+          # Initial message
+          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${SLACK_INITIAL_MESSAGE}\", \"channel\":\"${SLACK_CHANNEL}\"}" -H "Authorization: Bearer ${SLACK_TOKEN}" https://slack.com/api/chat.postMessage
 
-          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${SLACK_INITIAL_MESSAGE}\", \"channel\":\"${SLACK_CHANNEL}\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
-          curl -F file=@${TRIVY_OUTPUT} -F "initial_comment=${SLACK_TITLE}" -F channels=${SLACK_CHANNEL} -H "Authorization: Bearer ${SLACK_TOKEN}" https://slack.com/api/files.upload
+          # Upload file
+          UPLOAD_RESPONSE=$(curl -F file=@${TRIVY_OUTPUT} -F "initial_comment=${SLACK_TITLE}" -F channels=${SLACK_CHANNEL} -H "Authorization: Bearer ${SLACK_TOKEN}" https://slack.com/api/files.upload)
 
+          # Check if upload was successful
+          if [[ $(echo ${UPLOAD_RESPONSE} | jq -r '.ok') == "true" ]]; then
+            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${SLACK_UPLOAD_MESSAGE}\", \"channel\":\"${SLACK_CHANNEL}\"}" -H "Authorization: Bearer ${SLACK_TOKEN}" https://slack.com/api/chat.postMessage
+          else
+            echo "Failed to upload Trivy report to Slack: $(echo ${UPLOAD_RESPONSE} | jq -r '.error')"
+            exit 1
+          fi
 
       - name: Cleanup
         if: always()
